spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com          # SMTP 서버 호스트
    port: 587                     # SMTP 포트 (TLS)
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace