spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com          # SMTP 서버 호스트
    port: 587                     # SMTP 포트 (TLS)
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
