spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: create

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace