spring:
  application:
    name: module-api
  config:
    import:
      - classpath:application-infra.yml
      - classpath:application-security.yml
      - classpath:application-external-api.yml


springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true

server:
  port: 8080
  address: 0.0.0.0
